# Site settings
title: ocramz.github.io

description: > # this means to ignore newlines until "baseurl:"
  lambdas and large linear systems, oh my
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ocramz.github.io" # the base hostname & protocol for your site
twitter_username: ocramz_yo
github_username:  ocramz

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    # shortname: ocramz
    shortname: 
